### ISSUE TITLE
Crash when refreshing joining pane

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#1135]
Steps to reproduce

1. Navigate to http://organize.dev.zetkin.org/people/joining
2. Refresh browser

```
zetkinorganize_1     | [node] TypeError: Cannot read property 'formList' of undefined
zetkinorganize_1     | [node]     at mapStateToProps (/var/app/build/app/components/sections/people/JoiningPane.js:45:31)
zetkinorganize_1     | [node]     at Connect.configureFinalMapState (/var/app/node_modules/react-redux/lib/components/connect.js:155:27)
zetkinorganize_1     | [node]     at Connect.computeStateProps (/var/app/node_modules/react-redux/lib/components/connect.js:142:23)
zetkinorganize_1     | [node]     at Connect.updateStatePropsIfNeeded (/var/app/node_modules/react-redux/lib/components/connect.js:204:35)
zetkinorganize_1     | [node]     at Connect.render (/var/app/node_modules/react-redux/lib/components/connect.js:340:40)
zetkinorganize_1     | [node]     at /var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:793:21
zetkinorganize_1     | [node]     at measureLifeCyclePerf (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:792:25)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper._renderValidatedComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:819:32)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:359:30)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountChildren (/var/app/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
zetkinorganize_1     | [node]     at ReactDOMComponent._createContentMarkup (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountComponent (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountChildren (/var/app/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
zetkinorganize_1     | [node]     at ReactDOMComponent._createContentMarkup (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountComponent (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountChildren (/var/app/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
zetkinorganize_1     | [node]     at ReactDOMComponent._createContentMarkup (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountComponent (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountChildren (/var/app/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
zetkinorganize_1     | [node]     at ReactDOMComponent._createContentMarkup (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountComponent (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountChildren (/var/app/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
zetkinorganize_1     | [node]     at ReactDOMComponent._createContentMarkup (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountComponent (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountChildren (/var/app/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
zetkinorganize_1     | [node]     at ReactDOMComponent._createContentMarkup (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
zetkinorganize_1     | [node]     at ReactDOMComponent.mountComponent (/var/app/node_modules/react-dom/lib/ReactDOMComponent.js:524:29)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.performInitialMount (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
zetkinorganize_1     | [node]     at ReactCompositeComponentWrapper.mountComponent (/var/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
zetkinorganize_1     | [node]     at Object.mountComponent (/var/app/node_modules/react-dom/lib/ReactReconciler.js:43:35)
zetkinorganize_1     | [node]     at /var/app/node_modules/react-dom/lib/ReactServerRendering.js:43:36
zetkinorganize_1     | [node]     at ReactServerRenderingTransaction.perform (/var/app/node_modules/react-dom/lib/Transaction.js:141:20)
zetkinorganize_1     | [node]     at renderToStringImpl (/var/app/node_modules/react-dom/lib/ReactServerRendering.js:41:24)
zetkinorganize_1     | [node]     at Object.renderToString (/var/app/node_modules/react-dom/lib/ReactServerRendering.js:71:10)
zetkinorganize_1     | [node]     at renderReactPage (/var/app/build/app/server/app.js:236:37)
zetkinorganize_1     | [node]     at /var/app/build/app/server/app.js:210:9
zetkinorganize_1     | [node]     at Layer.handle [as handle_request] (/var/app/node_modules/express/lib/router/layer.js:95:5)
zetkinorganize_1     | [node]     at trim_prefix (/var/app/node_modules/express/lib/router/index.js:317:13)
zetkinorganize_1     | [node]     at /var/app/node_modules/express/lib/router/index.js:284:7
zetkinorganize_1     | [node]     at Function.process_params (/var/app/node_modules/express/lib/router/index.js:335:12)
zetkinorganize_1     | [node]     at next (/var/app/node_modules/express/lib/router/index.js:275:10)
zetkinorganize_1     | [node]     at next (/var/app/node_modules/express/lib/router/route.js:127:14)
zetkinorganize_1     | [node]     at app.get (/var/app/build/app/server/app.js:192:13)
zetkinorganize_1     | [node]     at Layer.handle [as handle_request] (/var/app/node_modules/express/lib/router/layer.js:95:5)
zetkinorganize_1     | [node]     at next (/var/app/node_modules/express/lib/router/route.js:137:13)
zetkinorganize_1     | [node]     at Route.dispatch (/var/app/node_modules/express/lib/router/route.js:112:3)
zetkinorganize_1     | [node]     at Layer.handle [as handle_request] (/var/app/node_modules/express/lib/router/layer.js:95:5)
zetkinorganize_1     | [node]     at /var/app/node_modules/express/lib/router/index.js:281:22
zetkinorganize_1     | [node]     at param (/var/app/node_modules/express/lib/router/index.js:354:14)
zetkinorganize_1     | [node]     at param (/var/app/node_modules/express/lib/router/index.js:365:14)
zetkinorganize_1     | [node]     at Function.process_params (/var/app/node_modules/express/lib/router/index.js:410:3)
zetkinorganize_1     | [node]     at next (/var/app/node_modules/express/lib/router/index.js:275:10)
zetkinorganize_1     | [node]     at /var/app/node_modules/express/lib/router/index.js:635:15
zetkinorganize_1     | [node]     at next (/var/app/node_modules/express/lib/router/index.js:260:14)
zetkinorganize_1     | [node]     at /var/app/build/app/server/locale.js:69:9
zetkinorganize_1     | [node]     at Layer.handle [as handle_request] (/var/app/node_modules/express/lib/router/layer.js:95:5)
zetkinorganize_1     | [node]     at trim_prefix (/var/app/node_modules/express/lib/router/index.js:317:13)
zetkinorganize_1     | [node]     at /var/app/node_modules/express/lib/router/index.js:284:7
zetkinorganize_1     | [node]     at Function.process_params (/var/app/node_modules/express/lib/router/index.js:335:12)
zetkinorganize_1     | [node]     at next (/var/app/node_modules/express/lib/router/index.js:275:10)
zetkinorganize_1     | [node]     at Promise.all.then (/var/app/build/app/server/datarouter.js:118:42)
zetkinorganize_1     | [node]     at process._tickCallback (internal/process/next_tick.js:68:7)
zetkinorganize_1     | [node] Mon, 26 Oct 2020 19:22:38 GMT express deprecated req.host: Use req.hostname instead at build/app/server/app.js:127:31
```

**Comment by richardolsson** [comment]
I can't reproduce this now, and looking at the error message, this seems to be caused by `state.joinForms` being `undefined`, which could never happen with the current codebase. I believe this was probably caused by old code running on the dev server for some reason.
